import {
  FaAws,
  FaBootstrap,
  FaCode,
  FaFigma,
  FaFileDownload,
  FaGithub,
  FaGitlab,
  FaHtml5,
  FaJava,
  FaLaravel,
  FaReact,
  FaSass,
  FaUsers,
} from "react-icons/fa";
import type { IconType } from "react-icons/lib";
import {
  SiAngular,
  SiAxios,
  SiDocker,
  SiFirebase,
  SiGooglecloud,
  SiGraphql,
  SiInertia,
  SiJavascript,
  SiLeaflet,
  SiMercadopago,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiPostgresql,
  SiPrisma,
  SiReactquery,
  SiRedux,
  SiShadcnui,
  SiSpring,
  SiSupabase,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

export const iconsMap: Record<string, IconType> = {
  typescript: SiTypescript,
  react: FaReact,
  redux: SiRedux,
  mui: SiMui,
  sass: FaSass,
  nextjs: SiNextdotjs,
  angular: SiAngular,
  figma: FaFigma,
  java: FaJava,
  spring: SiSpring,
  nestjs: SiNestjs,
  firebase: SiFirebase,
  download: FaFileDownload,
  aws: FaAws,
  docker: SiDocker,
  mongodb: SiMongodb,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  gcp: SiGooglecloud,
  github: FaGithub,
  gitlab: FaGitlab,
  laravel: FaLaravel,
  supabase: SiSupabase,
  html: FaHtml5,
  tailwindcss: SiTailwindcss,
  axios: SiAxios,
  bootstrap: FaBootstrap,
  inertia: SiInertia,
  leaflet: SiLeaflet,
  tanstack: SiReactquery,
  swagger: SiSwagger,
  javascript: SiJavascript,
  code: FaCode,
  graphql: SiGraphql,
  scrum: FaUsers,
  prisma: SiPrisma,
  shadcn: SiShadcnui,
  mercadopago: SiMercadopago,
};

export const getIcon = (icon: string) => {
  return iconsMap[icon];
};
