import {
  Briefcase,
  FileUser,
  GraduationCap,
  Lightbulb,
  Mail,
  MessageSquare,
  User,
} from "lucide-react";
import {
  FaAws,
  FaBootstrap,
  FaCode,
  FaFigma,
  FaFileDownload,
  FaGithub,
  FaGitlab,
  FaHtml5,
  FaJava,
  FaLaravel,
  FaLinkedin,
  FaReact,
  FaSass,
  FaUsers,
} from "react-icons/fa";
import type { IconType } from "react-icons/lib";
import {
  SiAngular,
  SiAxios,
  SiDocker,
  SiFirebase,
  SiGooglecloud,
  SiGraphql,
  SiInertia,
  SiJavascript,
  SiLeaflet,
  SiMercadopago,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiPostgresql,
  SiPrisma,
  SiReactquery,
  SiRedux,
  SiShadcnui,
  SiSpring,
  SiSupabase,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

export const iconsMap: Record<string, IconType> = {
  angular: SiAngular,
  aws: FaAws,
  axios: SiAxios,
  bootstrap: FaBootstrap,
  code: FaCode,
  docker: SiDocker,
  download: FaFileDownload,
  figma: FaFigma,
  firebase: SiFirebase,
  gcp: SiGooglecloud,
  github: FaGithub,
  gitlab: FaGitlab,
  graphql: SiGraphql,
  html: FaHtml5,
  inertia: SiInertia,
  java: FaJava,
  javascript: SiJavascript,
  laravel: FaLaravel,
  leaflet: SiLeaflet,
  linkedin: FaLinkedin,
  mercadopago: SiMercadopago,
  mongodb: SiMongodb,
  mui: SiMui,
  mysql: SiMysql,
  nestjs: SiNestjs,
  nextjs: SiNextdotjs,
  postgresql: SiPostgresql,
  prisma: SiPrisma,
  react: FaReact,
  redux: SiRedux,
  sass: FaSass,
  scrum: FaUsers,
  shadcn: SiShadcnui,
  spring: SiSpring,
  supabase: SiSupabase,
  swagger: SiSwagger,
  tailwindcss: SiTailwindcss,
  tanstack: SiReactquery,
  typescript: SiTypescript,
  user: User,
  email: Mail,
  message: MessageSquare,
  lightbulb: Lightbulb,
  briefcase: Briefcase,
  cv: FileUser,
  graduationcap: GraduationCap,
};

export const getIcon = (icon: string) => {
  return iconsMap[icon] || FaCode;
};
